#!/bin/bash

# Modern Blog Site - Quick Start Guide

echo ""
echo "╔═══════════════════════════════════════════════════════╗"
echo "║   🚀 Modern Blog Site - Quick Start                  ║"
echo "║                                                       ║"
echo "║   A modern, beautiful blog platform with Django      ║"
echo "║   and Tailwind CSS                                   ║"
echo "╚═══════════════════════════════════════════════════════╝"
echo ""

PROJECT_DIR="/home/ubuntu/Desktop/projects/modern-block-site"

echo "📁 Project Directory: $PROJECT_DIR"
echo ""

# Check if venv exists
if [ ! -d "$PROJECT_DIR/venv" ]; then
    echo "❌ Virtual environment not found!"
    echo "Creating virtual environment..."
    cd "$PROJECT_DIR"
    python3 -m venv venv
    echo "✅ Virtual environment created"
fi

echo ""
echo "📦 Activating virtual environment..."
cd "$PROJECT_DIR"
source venv/bin/activate

echo ""
echo "✅ Virtual environment activated"
echo ""
echo "════════════════════════════════════════════════════════"
echo "   🎯 ADMIN CREDENTIALS"
echo "════════════════════════════════════════════════════════"
echo ""
echo "Username: admin"
echo "Password: admin123"
echo ""
echo "Change this password immediately in production!"
echo ""
echo "════════════════════════════════════════════════════════"
echo "   📍 URLS"
echo "════════════════════════════════════════════════════════"
echo ""
echo "🌐 Blog Homepage:  http://localhost:8000/"
echo "📊 Admin Panel:    http://localhost:8000/admin/"
echo "🚪 Login:          http://localhost:8000/accounts/login/"
echo "📝 Register:       http://localhost:8000/accounts/register/"
echo ""
echo "════════════════════════════════════════════════════════"
echo "   🎨 FEATURES"
echo "════════════════════════════════════════════════════════"
echo ""
echo "✨ Features:"
echo "   • Modern, responsive design with Tailwind CSS"
echo "   • Post creation with featured images"
echo "   • Comments and reactions system"
echo "   • Search and category filtering"
echo "   • Admin dashboard for content management"
echo "   • User authentication and profiles"
echo "   • Newsletter subscription"
echo "   • Post visibility toggle"
echo "   • Scheduled publishing"
echo "   • Mobile-first design"
echo "   • Smooth animations and transitions"
echo ""
echo "🎨 Color Scheme:"
echo "   • Primary:   #54C4C7 (Teal)"
echo "   • BG:        #efeadd (Warm Beige)"
echo "   • Accent:    #2d8f92 (Dark Teal)"
echo ""
echo "════════════════════════════════════════════════════════"
echo "   ⚙️  GETTING STARTED"
echo "════════════════════════════════════════════════════════"
echo ""
echo "1. Start the server:"
echo "   python manage.py runserver"
echo ""
echo "2. Go to http://localhost:8000/"
echo ""
echo "3. Login to admin at http://localhost:8000/admin/"
echo "   (Username: admin, Password: admin123)"
echo ""
echo "4. Create some categories:"
echo "   - Go to Categories in admin"
echo "   - Add categories like 'Technology', 'Lifestyle', etc."
echo ""
echo "5. Create your first post:"
echo "   - Go to Posts in admin"
echo "   - Click 'Add Post'"
echo "   - Fill in title, content, excerpt, category"
echo "   - Upload a featured image (optional)"
echo "   - Set status to 'published'"
echo "   - Click Save"
echo ""
echo "6. View your blog:"
echo "   - Go to http://localhost:8000/"
echo "   - Your posts should appear!"
echo ""
echo "════════════════════════════════════════════════════════"
echo "   📚 USEFUL COMMANDS"
echo "════════════════════════════════════════════════════════"
echo ""
echo "# Run development server:"
echo "python manage.py runserver"
echo ""
echo "# Create superuser:"
echo "python manage.py createsuperuser"
echo ""
echo "# Make migrations:"
echo "python manage.py makemigrations"
echo ""
echo "# Apply migrations:"
echo "python manage.py migrate"
echo ""
echo "# Shell (test models):"
echo "python manage.py shell"
echo ""
echo "# Collect static files (production):"
echo "python manage.py collectstatic"
echo ""
echo "════════════════════════════════════════════════════════"
echo "   🔧 PROJECT STRUCTURE"
echo "════════════════════════════════════════════════════════"
echo ""
echo "config/              - Django settings and URLs"
echo "apps/blog/           - Blog app (posts, comments, reactions)"
echo "apps/accounts/       - User accounts and profiles"
echo "templates/           - HTML templates"
echo "static/              - CSS, JavaScript, images"
echo "media/               - User uploads"
echo "theme/               - Tailwind CSS theme"
echo "manage.py            - Django management"
echo "requirements.txt     - Python dependencies"
echo ""
echo "════════════════════════════════════════════════════════"
echo "   💡 NEXT STEPS"
echo "════════════════════════════════════════════════════════"
echo ""
echo "1. Customize colors in tailwind.config.js"
echo "2. Add your logo and branding"
echo "3. Create categories for your blog"
echo "4. Write your first blog post"
echo "5. Add comments and engage with readers"
echo "6. Deploy to production (see README.md)"
echo ""
echo "════════════════════════════════════════════════════════"
echo "   📖 DOCUMENTATION"
echo "════════════════════════════════════════════════════════"
echo ""
echo "See README.md for:"
echo "   • Full feature list"
echo "   • Installation instructions"
echo "   • Model documentation"
echo "   • Configuration options"
echo "   • Deployment guide"
echo ""
echo "════════════════════════════════════════════════════════"
echo ""
echo "🎉 Ready to go! Start the server with:"
echo ""
echo "   python manage.py runserver"
echo ""
echo "════════════════════════════════════════════════════════"
echo ""
