services:
  - type: web
    name: modern-block-site
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
